//! Project initialization and `.iris.toml` generation.
//!
//! Auto-detects project structure by scanning manifests (`Cargo.toml`,
//! `package.json`, `pyproject.toml`) and workspace layouts, then generates
//! a sensible `.iris.toml` configuration file with commented sections.
//!
//! # Examples
//!
//! ```no_run
//! use iris_core::init::write_config;
//! use std::path::Path;
//!
//! let detection = write_config(Path::new("."), false).unwrap();
//! println!("Detected: {}", detection.project_name);
//! ```

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use crate::code::bridge::detector::FrameworkDetector;
use crate::code::bridge::BridgeKind;
use crate::config::CORPUS_CONFIG_FILENAME;
use crate::workspace::{detect_all_workspaces, WorkspaceInfo, WorkspaceKind};

/// Summary of what was detected in a project directory.
#[derive(Debug, Clone)]
pub struct ProjectDetection {
    /// Human-readable project name (derived from directory name or manifest).
    pub project_name: String,
    /// Detected workspace layouts (Cargo, npm, pnpm, etc.).
    pub workspaces: Vec<WorkspaceInfo>,
    /// Detected cross-language bridge frameworks.
    pub bridges: Vec<BridgeKind>,
    /// Whether a Rust project was detected (`Cargo.toml` present).
    pub has_rust: bool,
    /// Whether a Node.js project was detected (`package.json` present).
    pub has_node: bool,
    /// Whether a Python project was detected (`pyproject.toml` or `setup.py`).
    pub has_python: bool,
    /// Relative paths to source directories.
    pub source_paths: Vec<String>,
    /// Relative paths to documentation files/directories.
    pub doc_paths: Vec<String>,
    /// Suggested ignore patterns for `.iris.toml`.
    pub ignore_patterns: Vec<String>,
}

/// Errors that can occur during `iris init`.
#[derive(Debug, thiserror::Error)]
pub enum InitError {
    /// The config file already exists and `--force` was not specified.
    #[error(".iris.toml already exists at {}", path.display())]
    AlreadyExists {
        /// Path to the existing config file.
        path: PathBuf,
    },

    /// Filesystem I/O error.
    #[error("I/O error: {source}")]
    Io {
        /// The underlying I/O error.
        #[from]
        source: std::io::Error,
    },
}

/// Detect project structure at `root` and build a [`ProjectDetection`].
///
/// Scans for manifests, workspace layouts, bridge frameworks, source
/// directories, and documentation files. All returned paths are relative
/// to `root`.
#[must_use]
pub fn detect_project(root: &Path) -> ProjectDetection {
    let workspaces = detect_all_workspaces(root);
    let bridges = FrameworkDetector::detect(root);

    let has_rust = root.join("Cargo.toml").exists();
    let has_node = root.join("package.json").exists();
    let has_python = root.join("pyproject.toml").exists() || root.join("setup.py").exists();

    let project_name = derive_project_name(root);
    let source_paths = detect_source_paths(root, &workspaces, has_rust, has_node, has_python);
    let doc_paths = detect_doc_paths(root);
    let ignore_patterns = default_ignore_patterns(has_rust, has_node, has_python);

    ProjectDetection {
        project_name,
        workspaces,
        bridges,
        has_rust,
        has_node,
        has_python,
        source_paths,
        doc_paths,
        ignore_patterns,
    }
}

/// Generate a commented TOML string from a [`ProjectDetection`].
///
/// The output includes inline comments explaining each section and is
/// suitable for writing directly to `.iris.toml`.
#[must_use]
pub fn render_toml(detection: &ProjectDetection) -> String {
    let mut out = String::new();

    // Header comment
    let _ = writeln!(out, "# iris corpus configuration — generated by `iris init`");

    // Detection summary
    let mut summary_parts = Vec::new();
    for ws in &detection.workspaces {
        summary_parts.push(format!("{} workspace ({} members)", ws.kind, ws.members.len()));
    }
    if detection.has_rust && !detection.workspaces.iter().any(|w| w.kind == WorkspaceKind::Cargo) {
        summary_parts.push("Rust crate".to_string());
    }
    if detection.has_node
        && !detection
            .workspaces
            .iter()
            .any(|w| matches!(w.kind, WorkspaceKind::Npm | WorkspaceKind::Yarn | WorkspaceKind::Pnpm))
    {
        summary_parts.push("Node.js project".to_string());
    }
    if detection.has_python {
        summary_parts.push("Python project".to_string());
    }
    if !detection.bridges.is_empty() {
        let bridge_names: Vec<_> = detection
            .bridges
            .iter()
            .map(|b| b.as_str().to_string())
            .collect();
        summary_parts.push(format!("bridges: {}", bridge_names.join(", ")));
    }
    if summary_parts.is_empty() {
        summary_parts.push("generic project".to_string());
    }

    let _ = writeln!(out, "# Detected: {}", summary_parts.join(", "));
    let _ = writeln!(out, "#");
    let _ = writeln!(
        out,
        "# iris automatically ignores target/, node_modules/, __pycache__, .git/, etc."
    );
    let _ = writeln!(
        out,
        "# Add extra ignore patterns below for project-specific exclusions."
    );
    let _ = writeln!(out);

    // [corpus] section
    let _ = writeln!(out, "[corpus]");

    // paths
    let _ = writeln!(out, "paths = [");
    if !detection.source_paths.is_empty() {
        let _ = writeln!(out, "    # Source code");
        for p in &detection.source_paths {
            let _ = writeln!(out, "    \"{p}\",");
        }
    }
    if !detection.doc_paths.is_empty() {
        if !detection.source_paths.is_empty() {
            let _ = writeln!(out);
        }
        let _ = writeln!(out, "    # Documentation");
        for p in &detection.doc_paths {
            let _ = writeln!(out, "    \"{p}\",");
        }
    }
    let _ = writeln!(out, "]");

    // ignore
    if !detection.ignore_patterns.is_empty() {
        let _ = writeln!(out);
        let _ = writeln!(out, "ignore = [");
        for p in &detection.ignore_patterns {
            let _ = writeln!(out, "    \"{p}\",");
        }
        let _ = writeln!(out, "]");
    }

    out
}

/// Write `.iris.toml` to `root`, failing if it already exists (unless `force`).
///
/// Returns the [`ProjectDetection`] so the caller can display what was found.
///
/// # Errors
///
/// Returns [`InitError::AlreadyExists`] if the file exists and `force` is false.
/// Returns [`InitError::Io`] on filesystem errors.
pub fn write_config(root: &Path, force: bool) -> Result<ProjectDetection, InitError> {
    let config_path = root.join(CORPUS_CONFIG_FILENAME);

    if config_path.exists() && !force {
        return Err(InitError::AlreadyExists { path: config_path });
    }

    let detection = detect_project(root);
    let toml_str = render_toml(&detection);
    std::fs::write(&config_path, toml_str)?;

    Ok(detection)
}

/// Derive the project name from the directory name or a manifest.
fn derive_project_name(root: &Path) -> String {
    // Try Cargo.toml [package] name first
    if let Some(name) = cargo_package_name(root) {
        return name;
    }
    // Try package.json name
    if let Some(name) = npm_package_name(root) {
        return name;
    }
    // Fall back to directory name
    root.file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("project")
        .to_string()
}

/// Extract `[package] name` from `Cargo.toml` if it's a single crate (not just a workspace root).
fn cargo_package_name(root: &Path) -> Option<String> {
    let content = std::fs::read_to_string(root.join("Cargo.toml")).ok()?;
    let parsed: toml::Value = toml::from_str(&content).ok()?;
    parsed
        .get("package")?
        .get("name")?
        .as_str()
        .map(String::from)
}

/// Extract `name` from `package.json`.
fn npm_package_name(root: &Path) -> Option<String> {
    let content = std::fs::read_to_string(root.join("package.json")).ok()?;
    let parsed: serde_json::Value = serde_json::from_str(&content).ok()?;
    parsed.get("name")?.as_str().map(String::from)
}

/// Detect source directories based on project layout.
fn detect_source_paths(
    root: &Path,
    workspaces: &[WorkspaceInfo],
    has_rust: bool,
    has_node: bool,
    has_python: bool,
) -> Vec<String> {
    let mut paths = Vec::new();

    // Workspace members first
    for ws in workspaces {
        match ws.kind {
            WorkspaceKind::Cargo => {
                for member in &ws.members {
                    if let Some(rel) = relative_path(root, &member.join("src")) {
                        if member.join("src").is_dir() {
                            paths.push(rel);
                        }
                    }
                }
            }
            WorkspaceKind::Npm
            | WorkspaceKind::Yarn
            | WorkspaceKind::Pnpm
            | WorkspaceKind::Turborepo
            | WorkspaceKind::Nx => {
                for member in &ws.members {
                    if let Some(rel) = find_js_source_dir(root, member) {
                        paths.push(rel);
                    }
                }
            }
        }
    }

    // If no workspace members contributed paths, check for standalone layouts
    if paths.is_empty() {
        if has_rust && root.join("src").is_dir() {
            paths.push("src".to_string());
        }
        if has_node {
            if let Some(rel) = find_js_source_dir(root, root) {
                if !paths.contains(&rel) {
                    paths.push(rel);
                }
            }
        }
        if has_python {
            if let Some(rel) = find_python_source_dir(root) {
                if !paths.contains(&rel) {
                    paths.push(rel);
                }
            }
        }
    }

    // Last resort: index everything
    if paths.is_empty() {
        paths.push(".".to_string());
    }

    paths
}

/// Find the JS/TS source directory for a package at `pkg_dir`.
fn find_js_source_dir(root: &Path, pkg_dir: &Path) -> Option<String> {
    for dir_name in &["src", "lib", "app"] {
        let candidate = pkg_dir.join(dir_name);
        if candidate.is_dir() {
            return relative_path(root, &candidate);
        }
    }
    None
}

/// Find the Python source directory at `root`.
fn find_python_source_dir(root: &Path) -> Option<String> {
    // PEP 517 src layout
    if root.join("src").is_dir() {
        return Some("src".to_string());
    }
    // Try to find a package dir matching the project name from pyproject.toml
    if let Some(name) = pyproject_name(root) {
        let pkg_dir = name.replace('-', "_");
        if root.join(&pkg_dir).is_dir() {
            return Some(pkg_dir);
        }
    }
    None
}

/// Extract `[project] name` from `pyproject.toml`.
fn pyproject_name(root: &Path) -> Option<String> {
    let content = std::fs::read_to_string(root.join("pyproject.toml")).ok()?;
    let parsed: toml::Value = toml::from_str(&content).ok()?;
    parsed
        .get("project")?
        .get("name")?
        .as_str()
        .map(String::from)
}

/// Detect documentation files and directories at `root`.
fn detect_doc_paths(root: &Path) -> Vec<String> {
    let candidates = ["README.md", "CHANGELOG.md", "DESIGN.md", "docs", "doc"];
    candidates
        .iter()
        .filter(|p| root.join(p).exists())
        .map(|p| (*p).to_string())
        .collect()
}

/// Build default ignore patterns based on detected languages.
fn default_ignore_patterns(has_rust: bool, has_node: bool, has_python: bool) -> Vec<String> {
    let mut patterns = Vec::new();

    if has_rust {
        patterns.push("*.snap".to_string());
    }
    if has_node {
        patterns.extend([
            "*.test.ts".to_string(),
            "*.spec.ts".to_string(),
            "*.test.js".to_string(),
            "*.spec.js".to_string(),
        ]);
    }
    if has_python {
        patterns.extend(["*_test.py".to_string(), "test_*.py".to_string()]);
    }

    patterns
}

/// Compute a relative path from `base` to `target`, returning `None` if
/// `target` is not under `base`.
fn relative_path(base: &Path, target: &Path) -> Option<String> {
    target
        .strip_prefix(base)
        .ok()
        .map(|rel| rel.to_string_lossy().to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    #[test]
    fn test_detect_cargo_workspace() {
        let tmp = TempDir::new().unwrap();
        let root = tmp.path();

        fs::write(
            root.join("Cargo.toml"),
            r#"
[workspace]
members = ["crate-a", "crate-b"]
"#,
        )
        .unwrap();

        fs::create_dir_all(root.join("crate-a/src")).unwrap();
        fs::create_dir_all(root.join("crate-b/src")).unwrap();

        let detection = detect_project(root);

        assert!(detection.has_rust);
        assert_eq!(detection.workspaces.len(), 1);
        assert_eq!(detection.workspaces[0].kind, WorkspaceKind::Cargo);
        assert!(detection.source_paths.contains(&"crate-a/src".to_string()));
        assert!(detection.source_paths.contains(&"crate-b/src".to_string()));
    }

    #[test]
    fn test_detect_single_rust_crate() {
        let tmp = TempDir::new().unwrap();
        let root = tmp.path();

        fs::write(
            root.join("Cargo.toml"),
            r#"
[package]
name = "my-crate"
version = "0.1.0"
"#,
        )
        .unwrap();
        fs::create_dir_all(root.join("src")).unwrap();

        let detection = detect_project(root);

        assert!(detection.has_rust);
        assert_eq!(detection.project_name, "my-crate");
        assert!(detection.workspaces.is_empty());
        assert_eq!(detection.source_paths, vec!["src"]);
    }

    #[test]
    fn test_detect_node_monorepo() {
        let tmp = TempDir::new().unwrap();
        let root = tmp.path();

        fs::write(
            root.join("package.json"),
            r#"{"name": "my-monorepo", "workspaces": ["packages/*"]}"#,
        )
        .unwrap();
        fs::create_dir_all(root.join("packages/app-a/src")).unwrap();
        fs::create_dir_all(root.join("packages/app-b/lib")).unwrap();

        let detection = detect_project(root);

        assert!(detection.has_node);
        assert!(!detection.workspaces.is_empty());
        assert!(detection
            .source_paths
            .contains(&"packages/app-a/src".to_string()));
        assert!(detection
            .source_paths
            .contains(&"packages/app-b/lib".to_string()));
    }

    #[test]
    fn test_detect_python_project() {
        let tmp = TempDir::new().unwrap();
        let root = tmp.path();

        fs::write(
            root.join("pyproject.toml"),
            r#"
[project]
name = "my-lib"
"#,
        )
        .unwrap();
        fs::create_dir_all(root.join("src")).unwrap();

        let detection = detect_project(root);

        assert!(detection.has_python);
        assert_eq!(detection.source_paths, vec!["src"]);
    }

    #[test]
    fn test_detect_polyglot() {
        let tmp = TempDir::new().unwrap();
        let root = tmp.path();

        fs::write(
            root.join("Cargo.toml"),
            r#"
[package]
name = "polyglot"
version = "0.1.0"
"#,
        )
        .unwrap();
        fs::write(root.join("package.json"), r#"{"name": "polyglot"}"#).unwrap();
        fs::create_dir_all(root.join("src")).unwrap();

        let detection = detect_project(root);

        assert!(detection.has_rust);
        assert!(detection.has_node);
    }

    #[test]
    fn test_detect_empty_dir() {
        let tmp = TempDir::new().unwrap();
        let detection = detect_project(tmp.path());

        assert!(!detection.has_rust);
        assert!(!detection.has_node);
        assert!(!detection.has_python);
        assert_eq!(detection.source_paths, vec!["."]);
    }

    #[test]
    fn test_render_toml_roundtrip() {
        let tmp = TempDir::new().unwrap();
        let root = tmp.path();

        fs::write(
            root.join("Cargo.toml"),
            r#"
[package]
name = "roundtrip"
version = "0.1.0"
"#,
        )
        .unwrap();
        fs::create_dir_all(root.join("src")).unwrap();
        fs::write(root.join("README.md"), "# Hello").unwrap();

        let detection = detect_project(root);
        let toml_str = render_toml(&detection);

        // Parse back as RepoConfig — should not error
        let parsed: crate::config::RepoConfig = toml::from_str(&toml_str).unwrap();
        assert!(parsed.corpus.paths.contains(&"src".to_string()));
        assert!(parsed.corpus.paths.contains(&"README.md".to_string()));
    }

    #[test]
    fn test_refuses_overwrite() {
        let tmp = TempDir::new().unwrap();
        let root = tmp.path();

        fs::write(root.join(CORPUS_CONFIG_FILENAME), "existing").unwrap();

        let result = write_config(root, false);
        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), InitError::AlreadyExists { .. }));
    }

    #[test]
    fn test_force_overwrites() {
        let tmp = TempDir::new().unwrap();
        let root = tmp.path();

        fs::write(root.join(CORPUS_CONFIG_FILENAME), "existing").unwrap();
        fs::create_dir_all(root.join("src")).unwrap();
        fs::write(
            root.join("Cargo.toml"),
            r#"[package]
name = "test"
version = "0.1.0"
"#,
        )
        .unwrap();

        let result = write_config(root, true);
        assert!(result.is_ok());

        let content = fs::read_to_string(root.join(CORPUS_CONFIG_FILENAME)).unwrap();
        assert!(content.contains("[corpus]"));
    }

    #[test]
    fn test_doc_paths_detected() {
        let tmp = TempDir::new().unwrap();
        let root = tmp.path();

        fs::write(root.join("README.md"), "# Hello").unwrap();
        fs::create_dir_all(root.join("docs")).unwrap();

        let detection = detect_project(root);

        assert!(detection.doc_paths.contains(&"README.md".to_string()));
        assert!(detection.doc_paths.contains(&"docs".to_string()));
    }

    #[test]
    fn test_ignore_patterns_per_language() {
        let patterns = default_ignore_patterns(true, true, false);
        assert!(patterns.contains(&"*.snap".to_string()));
        assert!(patterns.contains(&"*.test.ts".to_string()));
        assert!(!patterns.iter().any(|p| p.contains("_test.py")));

        let py_patterns = default_ignore_patterns(false, false, true);
        assert!(py_patterns.contains(&"*_test.py".to_string()));
    }
}
