//! Org invites (F3.1b-i — link generation + acceptance).
//!
//! Magic-link invites for new org members. Mirrors the
//! [`super::repo`] split: handlers in [`super::routes`] stay focused on
//! HTTP shape + authz; this module owns the SQL.
//!
//! # Token discipline
//!
//! - The raw token is generated by [`create_invite`] from the OS RNG
//!   and returned ONCE in the response. The DB only stores the
//!   SHA-256 hex digest.
//! - [`consume_invite`] hashes the candidate token before lookup. A
//!   leaked DB dump therefore cannot be used to join an org —
//!   attackers would have to brute-force the SHA-256 preimage of a
//!   256-bit random token, which is computationally infeasible.
//!
//! # Acceptance is transactional
//!
//! [`consume_invite`] runs in a single transaction:
//!
//! 1. Lock the invite row (`SELECT ... FOR UPDATE`).
//! 2. Reject if it's already `accepted_at IS NOT NULL` or past
//!    `expires_at`.
//! 3. Insert into `org_members` (with `ON CONFLICT DO NOTHING` to
//!    cover the corner case of a user already in the org).
//! 4. Mark the invite `accepted_at = now()`.
//!
//! A concurrent attempt sees the locked row and gets `Err(AlreadyAccepted)`
//! after the first commit lands — never two inserts for the same invite.

use deadpool_postgres::Pool;
use sha2::{Digest, Sha256};
use std::fmt::Write as _;
use std::time::Duration;

use super::repo::OrgError;

/// Default TTL applied when [`create_invite`] is called without an
/// explicit override. Mirrors common `SaaS` invite-link windows
/// (GitHub: 7 days, Vercel: 14 days; we pick the conservative end).
pub const DEFAULT_INVITE_TTL: Duration = Duration::from_secs(7 * 24 * 60 * 60);

/// Number of random bytes behind the invite token. 32 bytes → 256
/// bits of entropy, well past the 128-bit floor for unguessable
/// secrets even under accelerated brute-force.
const TOKEN_ENTROPY_BYTES: usize = 32;

/// A single row from the `org_invites` table. Shape mirrors
/// [`super::repo::OrgRow`]: the canonical UUID fields land as
/// `String` for serde symmetry.
#[derive(Debug, Clone)]
pub struct InviteRow {
    /// `org_invites.id`.
    pub id: String,
    /// `org_invites.org_id`.
    pub org_id: String,
    /// `org_invites.email` — recipient address; the magic link is
    /// scoped to this address only in the F3.1b-ii email step. F3.1b-i
    /// returns the URL directly so we don't compare against the
    /// authenticated user's email — that gate is a feature of the
    /// email-delivery half.
    pub email: String,
    /// One of `'owner'`, `'admin'`, `'member'`. Defaults to `'member'`.
    pub role: String,
    /// `org_invites.invited_by` — the user that `POSTed` the invite.
    pub invited_by: String,
    /// `org_invites.expires_at` as ISO-8601 UTC. Consume time
    /// compares server-side via Postgres' `now() > expires_at`.
    pub expires_at: String,
}

/// Wrapper returned by [`create_invite`]: the persisted row plus the
/// one-time raw token. Callers MUST serialise the token into the
/// invite URL immediately and never log it — the DB only holds its
/// hash.
#[derive(Debug)]
pub struct CreatedInvite {
    pub row: InviteRow,
    pub raw_token: String,
}

/// Insert a new invite row with a freshly-minted token.
///
/// `inviter_user_id` is the OAuth-resolved subject of the caller —
/// the routes layer authorizes this against `member_role` (owner /
/// admin only) BEFORE calling here.
///
/// # Errors
///
/// - [`OrgError::Sql`] on DB failure.
/// - [`OrgError::GetConn`] when the pool is empty.
pub async fn create_invite(
    pool: &Pool,
    org_id: &str,
    email: &str,
    role: &str,
    invited_by_user_id: &str,
    ttl: Duration,
) -> Result<CreatedInvite, OrgError> {
    let raw_token = mint_token();
    let token_hash = hash_token(&raw_token);
    // Postgres `make_interval(secs => …)` wants double precision; the
    // u64 secs comfortably fits in an f64 for any practical TTL
    // (centuries of seconds round-trip without loss).
    #[allow(clippy::cast_precision_loss)]
    let ttl_secs_f64 = ttl.as_secs() as f64;

    let client = pool
        .get()
        .await
        .map_err(|e| OrgError::GetConn(format!("create_invite: {e}")))?;

    let row = client
        .query_one(
            "INSERT INTO org_invites
               (org_id, email, token_hash, role, invited_by, expires_at)
             VALUES (
                 $1::uuid, $2, $3, $4,
                 $5::uuid,
                 now() + make_interval(secs => $6::double precision)
             )
             RETURNING
                 id::text          AS id_text,
                 org_id::text      AS org_id_text,
                 email,
                 role,
                 invited_by::text  AS invited_by_text,
                 to_char(expires_at AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"')
                                     AS expires_at_iso",
            &[
                &org_id,
                &email,
                &token_hash,
                &role,
                &invited_by_user_id,
                &ttl_secs_f64,
            ],
        )
        .await
        .map_err(|e| OrgError::Sql(format!("insert invite: {e}")))?;

    let parsed = InviteRow {
        id: row.get("id_text"),
        org_id: row.get("org_id_text"),
        email: row.get("email"),
        role: row.get("role"),
        invited_by: row.get("invited_by_text"),
        expires_at: row.get("expires_at_iso"),
    };
    Ok(CreatedInvite {
        row: parsed,
        raw_token,
    })
}

/// Outcome of [`consume_invite`].
#[derive(Debug, Clone)]
pub enum ConsumeOutcome {
    /// New membership inserted. Caller should redirect / display
    /// success.
    Accepted { org_id: String, role: String },
    /// Invite was already accepted (or matches no row). Treated as a
    /// hard fail at the HTTP boundary — recipient must request a
    /// fresh link.
    AlreadyAccepted,
    /// Invite exists but is past `expires_at`. Same client-facing
    /// outcome as `AlreadyAccepted` (the link is dead) but logged
    /// distinctly.
    Expired,
    /// Token didn't match any row. Probably typo or replay against
    /// a row that was hard-deleted by a future retention cron.
    Unknown,
}

/// Look up an invite by raw token, validate it, and insert the
/// matching `org_members` row in a single transaction.
///
/// `user_id` is the authenticated user (the recipient who clicked
/// the link AND completed GitHub sign-in). We do NOT compare against
/// `org_invites.email` in this half — that comparison lands in
/// F3.1b-ii when email delivery enforces "only the addressed
/// recipient can accept". F3.1b-i treats the link itself as a
/// bearer secret (256 bits of entropy gates that).
///
/// # Errors
///
/// - [`OrgError::Sql`] / [`OrgError::GetConn`] on DB issues. Logical
///   outcomes (expired / unknown / already accepted) are NOT errors —
///   they come back as [`ConsumeOutcome`] variants so the HTTP layer
///   can format them.
pub async fn consume_invite(
    pool: &Pool,
    raw_token: &str,
    user_id: &str,
) -> Result<ConsumeOutcome, OrgError> {
    let token_hash = hash_token(raw_token);

    let mut conn = pool
        .get()
        .await
        .map_err(|e| OrgError::GetConn(format!("consume_invite: {e}")))?;
    let tx = conn
        .transaction()
        .await
        .map_err(|e| OrgError::Sql(format!("begin txn: {e}")))?;

    // FOR UPDATE so concurrent acceptances serialise — the loser sees
    // accepted_at set on its re-read.
    let Some(row) = tx
        .query_opt(
            "SELECT
                 id::text          AS id_text,
                 org_id::text      AS org_id_text,
                 role,
                 accepted_at,
                 (now() > expires_at) AS is_expired
             FROM org_invites
             WHERE token_hash = $1
             FOR UPDATE",
            &[&token_hash],
        )
        .await
        .map_err(|e| OrgError::Sql(format!("lookup invite: {e}")))?
    else {
        tx.commit()
            .await
            .map_err(|e| OrgError::Sql(format!("commit (unknown): {e}")))?;
        return Ok(ConsumeOutcome::Unknown);
    };

    let accepted_at: Option<std::time::SystemTime> = row.try_get("accepted_at").ok();
    if accepted_at.is_some() {
        tx.commit()
            .await
            .map_err(|e| OrgError::Sql(format!("commit (already): {e}")))?;
        return Ok(ConsumeOutcome::AlreadyAccepted);
    }
    let is_expired: bool = row.get("is_expired");
    if is_expired {
        tx.commit()
            .await
            .map_err(|e| OrgError::Sql(format!("commit (expired): {e}")))?;
        return Ok(ConsumeOutcome::Expired);
    }

    let invite_id: String = row.get("id_text");
    let org_id: String = row.get("org_id_text");
    let role: String = row.get("role");

    // Insert membership. ON CONFLICT covers the corner case of a user
    // already being a member (e.g. a re-invite they don't realise they
    // already accepted under another invite). The invite itself still
    // closes — accepting an "extra" link should be idempotent.
    tx.execute(
        "INSERT INTO org_members (org_id, user_id, role)
         VALUES ($1::uuid, $2::uuid, $3)
         ON CONFLICT (org_id, user_id) DO NOTHING",
        &[&org_id, &user_id, &role],
    )
    .await
    .map_err(|e| OrgError::Sql(format!("insert membership: {e}")))?;

    tx.execute(
        "UPDATE org_invites SET accepted_at = now() WHERE id = $1::uuid",
        &[&invite_id],
    )
    .await
    .map_err(|e| OrgError::Sql(format!("mark accepted: {e}")))?;

    tx.commit()
        .await
        .map_err(|e| OrgError::Sql(format!("commit (accept): {e}")))?;

    Ok(ConsumeOutcome::Accepted { org_id, role })
}

/// Mint a fresh token: `TOKEN_ENTROPY_BYTES` of CSPRNG output,
/// base64url-no-pad. Mirrors the `random_url_safe_id` helper in
/// `auth::github_signin` for shape consistency.
fn mint_token() -> String {
    let mut buf = [0u8; TOKEN_ENTROPY_BYTES];
    getrandom::fill(&mut buf).expect("OS RNG must be available for invite tokens");
    base64_url_no_pad(&buf)
}

/// SHA-256 of the raw token, hex-encoded (lowercase). Used as the
/// row's `token_hash` column AND the lookup key on consume.
fn hash_token(raw: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(raw.as_bytes());
    let digest = hasher.finalize();
    let mut out = String::with_capacity(digest.len() * 2);
    for b in digest {
        let _ = write!(out, "{b:02x}");
    }
    out
}

fn base64_url_no_pad(data: &[u8]) -> String {
    const ALPHABET: &[u8; 64] =
        b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
    let mut out = String::with_capacity((data.len() * 4).div_ceil(3));
    let mut i = 0;
    while i < data.len() {
        let b0 = u32::from(data[i]);
        let b1 = if i + 1 < data.len() {
            u32::from(data[i + 1])
        } else {
            0
        };
        let b2 = if i + 2 < data.len() {
            u32::from(data[i + 2])
        } else {
            0
        };
        let triple = (b0 << 16) | (b1 << 8) | b2;
        out.push(ALPHABET[((triple >> 18) & 0x3F) as usize] as char);
        out.push(ALPHABET[((triple >> 12) & 0x3F) as usize] as char);
        if i + 1 < data.len() {
            out.push(ALPHABET[((triple >> 6) & 0x3F) as usize] as char);
        }
        if i + 2 < data.len() {
            out.push(ALPHABET[(triple & 0x3F) as usize] as char);
        }
        i += 3;
    }
    out
}

#[cfg(test)]
mod tests {
    //! Pure-Rust tests of the token helpers. Postgres-integration
    //! tests live in [`super::super::routes::tests`] gated on
    //! `MINISTR_TEST_PG_URL`.

    use super::*;
    use std::collections::HashSet;

    #[test]
    fn token_has_minimum_entropy_alphabet() {
        let tok = mint_token();
        // 32 bytes → ceil(32 * 4 / 3) = 43 base64url chars.
        assert!(
            (43..=128).contains(&tok.len()),
            "unexpected token length: {}",
            tok.len()
        );
        assert!(
            tok.bytes()
                .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_'),
            "non-base64url byte in token"
        );
    }

    #[test]
    fn mint_token_is_random() {
        let n = 64;
        let tokens: HashSet<String> = (0..n).map(|_| mint_token()).collect();
        assert_eq!(tokens.len(), n, "duplicate tokens — RNG is broken");
    }

    #[test]
    fn hash_token_is_deterministic_and_hex() {
        let h1 = hash_token("hello-world");
        let h2 = hash_token("hello-world");
        assert_eq!(h1, h2);
        assert_eq!(h1.len(), 64, "SHA-256 hex is 64 chars");
        assert!(h1.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn hash_token_differs_for_different_inputs() {
        let a = hash_token("token-a");
        let b = hash_token("token-b");
        assert_ne!(a, b);
    }
}
