#!/usr/bin/env python3
"""Rebrand iris -> ministr across the repo.

Strategy:
  1. git mv the six crate directories (iris-* -> ministr-*).
  2. git mv specific filename artifacts (.iris.toml, iris_version.py, etc.).
  3. For every git-tracked TEXT file, read content and apply replacements
     in a specific order (longest-match first to avoid clobbering).
  4. Write back atomically.

Run once from the repo root. Idempotent: running a second time is a no-op
because all patterns have already been substituted.

Exclusions:
  - .git/ tree (not tracked anyway)
  - Cargo.lock (regenerated by cargo)
  - binary assets: .png, .jpg, .ico, .woff, .woff2, .otf, .ttf, .ipynb
  - the script itself

The user directive is "no mention of iris at all" so design-archive/ IS
rewritten too.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Replacements applied in order. Longer / more specific patterns first so
# they don't get partially consumed by a later broader pattern.
REPLACEMENTS: list[tuple[str, str]] = [
    # module paths and URIs (highest specificity)
    ("iris-rs", "ministr-rs"),
    ("dev.iris/", "dev.ministr/"),
    ("iris_core", "ministr_core"),
    ("iris_api", "ministr_api"),
    ("iris_daemon", "ministr_daemon"),
    ("iris_mcp", "ministr_mcp"),
    ("iris_cli", "ministr_cli"),
    ("iris_app", "ministr_app"),
    ("iris-core", "ministr-core"),
    ("iris-api", "ministr-api"),
    ("iris-daemon", "ministr-daemon"),
    ("iris-mcp", "ministr-mcp"),
    ("iris-cli", "ministr-cli"),
    ("iris-app", "ministr-app"),
    (".iris.toml", ".ministr.toml"),
    ("IRIS_", "MINISTR_"),
    # CamelCase Rust identifier prefix. Only replace 'Iris' when directly
    # followed by another uppercase letter (i.e., CamelCase identifier).
    # We handle this with a sentinel loop below, not via plain str.replace.
    # CamelCase is handled specially — see apply_replacements.
    # Remaining iris_ and Iris_ prefixes (tool names, test names)
    ("iris_", "ministr_"),
    ("Iris_", "Ministr_"),
    # Bare word "iris" — apply last. Word-boundary logic also handled below.
]

# Files with "iris" in the NAME that need to be moved. Entries are tried in
# order; missing entries are skipped with a warning, not a fatal error.
FILE_RENAMES: list[tuple[str, str]] = [
    (".iris.toml", ".ministr.toml"),
    (".github/hooks/iris-enforce.json", ".github/hooks/ministr-enforce.json"),
    (
        "docs-next/components/landing/what-iris-isnt.tsx",
        "docs-next/components/landing/what-ministr-isnt.tsx",
    ),
    ("examples/pyo3-project.iris.toml", "examples/pyo3-project.ministr.toml"),
    (
        "examples/react-node-monorepo.iris.toml",
        "examples/react-node-monorepo.ministr.toml",
    ),
    ("examples/rust-workspace.iris.toml", "examples/rust-workspace.ministr.toml"),
    ("examples/tauri-app.iris.toml", "examples/tauri-app.ministr.toml"),
    ("homebrew/iris.rb", "homebrew/ministr.rb"),
    ("ministr-app/com.iris.app.plist", "ministr-app/com.ministr.app.plist"),
    (
        "ministr-app/src-tauri/resources/com.iris.desktop.plist",
        "ministr-app/src-tauri/resources/com.ministr.desktop.plist",
    ),
    ("windsurf/rules/iris-lang-rules.md", "windsurf/rules/ministr-lang-rules.md"),
    ("windsurf/rules/iris.md", "windsurf/rules/ministr.md"),
    # Repo-local .claude/rules files (may be gitignored but still present).
    (".claude/rules/iris-playbook.md", ".claude/rules/ministr-playbook.md"),
    (".claude/rules/iris-scope.md", ".claude/rules/ministr-scope.md"),
    (".claude/rules/iris-lang-rules.md", ".claude/rules/ministr-lang-rules.md"),
]

# Six crate directory renames.
DIR_RENAMES: list[tuple[str, str]] = [
    ("iris-core", "ministr-core"),
    ("iris-api", "ministr-api"),
    ("iris-daemon", "ministr-daemon"),
    ("iris-mcp", "ministr-mcp"),
    ("iris-cli", "ministr-cli"),
    ("iris-app", "ministr-app"),
]

# File extensions to treat as text.
TEXT_EXTS = {
    ".rs", ".toml", ".md", ".mdx", ".yml", ".yaml", ".json", ".js",
    ".mjs", ".ts", ".tsx", ".html", ".css", ".py", ".sh", ".rb",
    ".lock", ".xml", ".svg", ".plist", ".swift", ".txt", ".env",
    ".dockerignore", ".gitignore",
}
# Filenames without extension that are still text.
TEXT_NAMES = {
    "Cargo.toml", "Dockerfile", "justfile", "LICENSE-MIT", "LICENSE-APACHE",
    "rustfmt.toml",
}

BINARY_EXTS = {
    ".png", ".jpg", ".jpeg", ".gif", ".ico", ".woff", ".woff2", ".otf",
    ".ttf", ".ipynb", ".pdf", ".zip", ".tar", ".gz",
}

SELF = Path(__file__).resolve()


def run(*cmd: str, check: bool = True) -> str:
    result = subprocess.run(
        list(cmd), cwd=REPO, capture_output=True, text=True
    )
    if check and result.returncode != 0:
        print(f"FAILED: {' '.join(cmd)}", file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        sys.exit(result.returncode)
    return result.stdout


def is_tracked(relpath: str) -> bool:
    """True if git tracks this path."""
    out = subprocess.run(
        ["git", "ls-files", "--error-unmatch", relpath],
        cwd=REPO,
        capture_output=True,
        text=True,
    )
    return out.returncode == 0


def move_path(old: str, new: str) -> None:
    """git mv if tracked, plain os.rename if just untracked."""
    src = REPO / old
    dst = REPO / new
    if not src.exists():
        if dst.exists():
            print(f"  (already renamed: {new})")
        else:
            print(f"  (skip: {old} missing)")
        return
    if dst.exists():
        print(f"  (conflict: {new} already exists — leaving {old})")
        return
    dst.parent.mkdir(parents=True, exist_ok=True)
    if is_tracked(old):
        print(f"git mv {old} {new}")
        run("git", "mv", old, new)
    else:
        print(f"mv   {old} {new}")
        src.rename(dst)


def git_tracked() -> list[Path]:
    out = run("git", "ls-files", "-z")
    return [REPO / p for p in out.split("\0") if p]


def is_text(path: Path) -> bool:
    if path.name in TEXT_NAMES:
        return True
    if path.suffix in TEXT_EXTS:
        return True
    if path.suffix in BINARY_EXTS:
        return False
    # No extension, unknown: peek at first bytes.
    try:
        with path.open("rb") as fh:
            chunk = fh.read(4096)
        return b"\0" not in chunk
    except OSError:
        return False


def apply_replacements(text: str) -> str:
    out = text
    for old, new in REPLACEMENTS:
        out = out.replace(old, new)
    # Handle CamelCase Iris<UpperOrDigit> -> Ministr<...>.
    # Also handle `Iris` at end of word (like "LoadIris") if it ever occurs.
    # Regex keeps it surgical.
    import re

    # Replace Iris followed by uppercase letter or digit (CamelCase token).
    out = re.sub(r"\bIris(?=[A-Z0-9])", "Ministr", out)
    # Replace standalone "Iris" word (PascalCase bare term).
    out = re.sub(r"\bIris\b", "Ministr", out)
    # Replace standalone "iris" word (prose, CLI help, help text).
    out = re.sub(r"\biris\b", "ministr", out)
    # Replace standalone "IRIS" word (acronym uses).
    out = re.sub(r"\bIRIS\b", "MINISTR", out)
    return out


def rename_dirs() -> None:
    for old, new in DIR_RENAMES:
        move_path(old, new)


def rename_files() -> None:
    for old, new in FILE_RENAMES:
        move_path(old, new)


def extra_untracked_paths() -> list[Path]:
    """Files that exist but aren't git-tracked, yet still need rewriting.

    .claude/rules/ is gitignored in this repo but contains rules text that
    still references iris_* tool names and must be updated.
    """
    candidates = [
        REPO / ".claude" / "rules" / "ministr-playbook.md",
        REPO / ".claude" / "rules" / "ministr-scope.md",
        REPO / ".claude" / "rules" / "ministr-lang-rules.md",
        REPO / ".claude" / "rules" / "tools.md",
        REPO / ".claude" / "rules" / "workflow.md",
        REPO / ".claude" / "rules" / "conventions.md",
    ]
    return [p for p in candidates if p.exists()]


def rewrite_contents() -> None:
    changed = 0
    skipped = 0
    seen: set[Path] = set()
    for path in list(git_tracked()) + extra_untracked_paths():
        real = path.resolve()
        if real in seen:
            continue
        seen.add(real)
        if real == SELF:
            continue
        if not path.exists():  # broken or already moved
            continue
        if not is_text(path):
            skipped += 1
            continue
        try:
            original = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            skipped += 1
            continue
        new = apply_replacements(original)
        if new != original:
            path.write_text(new, encoding="utf-8")
            changed += 1
    print(f"rewrote {changed} files; skipped {skipped} non-text")


def main() -> int:
    if not (REPO / ".git").is_dir():
        print("not a git repo root", file=sys.stderr)
        return 1
    print("== renaming crate directories ==")
    rename_dirs()
    print("== renaming named files ==")
    rename_files()
    print("== rewriting file contents ==")
    rewrite_contents()
    print("done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
